---
- name: Deploy monitoring tools
  import_playbook: pokerops.monitoring.tools.install

- name: Deploy Vector agent
  import_playbook: pokerops.monitoring.vector.install

- name: Deploy beats agents
  import_playbook: pokerops.monitoring.beats.install
